### ISSUE TITLE
Verify recursive type definition

### ISSUE THREAD

**Issue by dansanduleac** [palantir/conjure-verification#32]
This is to test that clients can successfully handle such definitions at runtime.

Aimed to ensure that this fix will work for python: https://github.com/palantir/conjure-python/pull/9.

Example:
```yaml
types:
  definitions:
    default-package: whatever
    objects:
      ZigOrZag:
        union:
          zig: Zig
          zag: Zag
      Zig:
        object:
          recursive: ZigOrZag
      Zag:
        alias: string
```

(and an endpoint that references `ZigOrZag`)
